grammarData = [
    // 1. 時間 (Time)
    {"id":1,"level":"N1","grammar_display":"〜や否や / 〜や","grammar_answer":"や否や","connection":"動詞の辞書形 + や否や","sentence_parts":["空が暗くなる","、大粒の雨が降り始めた。"]},
    {"id":2,"level":"N1","grammar_display":"〜が早いか","grammar_answer":"が早いか","connection":"動詞の辞書形 / た形 + が早いか","sentence_parts":["ベルが鳴る","、生徒たちは教室を飛び出した。"]},
    {"id":3,"level":"N1","grammar_display":"〜なり","grammar_answer":"なり","connection":"動詞の辞書形 + なり","sentence_parts":["彼はコーヒーを一口飲む","、吐き出してしまった。"]},
    {"id":4,"level":"N1","grammar_display":"〜そばから","grammar_answer":"そばから","connection":"動詞の辞書形 / た形 + そばから","sentence_parts":["子供はおもちゃを片付けた","、また散らかす。"]},
    {"id":5,"level":"N1","grammar_display":"〜てからというもの","grammar_answer":"てからというもの","connection":"動詞て形 + からというもの","sentence_parts":["日本へ来","、国に一度も帰っていない。"]},
    {"id":6,"level":"N1","grammar_display":"〜を限りに","grammar_answer":"を限りに","connection":"名詞 + を限りに","sentence_parts":["今日","、タバコをやめることにした。"]},
    {"id":7,"level":"N1","grammar_display":"〜を皮切りに","grammar_answer":"を皮切りに","connection":"名詞 + を皮切りに（して）","sentence_parts":["東京公演","、全国ツアーが始まった。"]},
    {"id":8,"level":"N1","grammar_display":"〜に至るまで","grammar_answer":"に至るまで","connection":"名詞 + から + 名詞 + に至るまで","sentence_parts":["私の学校は、服装から髪型","厳しい規則がある。"]},
    {"id":9,"level":"N2","grammar_display":"〜ところだ","grammar_answer":"ところだ","connection":"動詞の辞書形 + ところだ","sentence_parts":["ちょうど今から食事に行く","。"]},
    {"id":10,"level":"N2","grammar_display":"〜（ている）ところだ","grammar_answer":"ているところだ","connection":"動詞のている形 + ところだ","sentence_parts":["今、レポートを書い","。"]},
    {"id":11,"level":"N2","grammar_display":"〜（た）ところだ","grammar_answer":"たところだ","connection":"動詞のた形 + ところだ","sentence_parts":["たった今、空港に着い","。"]},
    {"id":12,"level":"N2","grammar_display":"〜ところに","grammar_answer":"ところに","connection":"動詞の辞書形/ている形/た形 + ところに","sentence_parts":["お風呂に入っている","、電話がかかってきた。"]},
    {"id":13,"level":"N2","grammar_display":"〜ところへ","grammar_answer":"ところへ","connection":"動詞の辞書形/ている形/た形 + ところへ","sentence_parts":["出かけようとした","、友達が訪ねてきた。"]},
    {"id":14,"level":"N2","grammar_display":"〜ところを","grammar_answer":"ところを","connection":"動詞の辞書形/ている形/た形 + ところを","sentence_parts":["犯人が逃げようとしている","、警察官に捕まえられた。"]},
    {"id":15,"level":"N2","grammar_display":"〜最中だ","grammar_answer":"最中に","connection":"動詞のている形 / 名詞の + 最中だ","sentence_parts":["スピーチの","、携帯電話が鳴ってしまった。"]},
    {"id":16,"level":"N2","grammar_display":"〜たびに","grammar_answer":"たびに","connection":"動詞の辞書形 / 名詞の + たびに","sentence_parts":["この写真を見る","、楽しかった学生時代を思い出す。"]},
    {"id":17,"level":"N2","grammar_display":"〜うちに","grammar_answer":"うちに","connection":"動詞の辞書形/ている形/ない形 / イ形容詞 / ナ形容詞な / 名詞の + うちに","sentence_parts":["忘れない","、メモしておこう。"]},
    {"id":18,"level":"N2","grammar_display":"〜か～ないかのうちに","grammar_answer":"か〜ないかのうちに","connection":"動詞の辞書形 + か + 動詞のない形 + かのうちに","sentence_parts":["彼はベッドに横になる","、眠ってしまった。"]},
    {"id":19,"level":"N2","grammar_display":"〜かと思うと","grammar_answer":"かと思うと","connection":"動詞のた形 + かと思うと","sentence_parts":["赤ちゃんはさっきまで泣いていた","、もう笑っている。"]},
    {"id":20,"level":"N2","grammar_display":"〜た途端（に）","grammar_answer":"途端に","connection":"動詞のた形 + 途端（に）","sentence_parts":["ドアを開けた","、猫が飛び出してきた。"]},
    {"id":21,"level":"N2","grammar_display":"〜次第","grammar_answer":"次第","connection":"動詞のます形 + 次第","sentence_parts":["詳しいことが分かり","、ご連絡いたします。"]},
    {"id":22,"level":"N2","grammar_display":"〜て以来","grammar_answer":"て以来","connection":"動詞のて形 + 以来","sentence_parts":["卒業し","、一度も彼に会っていない。"]},
    {"id":23,"level":"N2","grammar_display":"〜てはじめて","grammar_answer":"てはじめて","connection":"動詞のて形 + はじめて","sentence_parts":["病気になっ","、健康のありがたみがわかった。"]},
    {"id":24,"level":"N2","grammar_display":"〜にあたって","grammar_answer":"にあたり","connection":"動詞の辞書形 / 名詞 + にあたって / にあたり","sentence_parts":["開店","、ひとことご挨拶申し上げます。"]},
    {"id":25,"level":"N2","grammar_display":"〜際に","grammar_answer":"際に","connection":"動詞の辞書形/た形 / 名詞の + 際に","sentence_parts":["お申し込みの","、住所と氏名をお知らせください。"]},
    {"id":26,"level":"N2","grammar_display":"〜に際して","grammar_answer":"に際して","connection":"動詞の辞書形 / 名詞 + に際して","sentence_parts":["契約","、注意すべき点を説明します。"]},
    {"id":27,"level":"N2","grammar_display":"〜をきっかけに","grammar_answer":"をきっかけに","connection":"名詞 + をきっかけに","sentence_parts":["大学入学","、一人暮らしを始めた。"]},
    {"id":28,"level":"N1","grammar_display":"〜にあって","grammar_answer":"にあって","connection":"名詞 + にあって","sentence_parts":["この困難な状況","、彼は冷静さを失わなかった。"]},
    // 2. 原因・理由・結果
    {"id":29,"level":"N1","grammar_display":"〜とあって","grammar_answer":"とあって","connection":"普通形（ナ形容詞・名詞 + とあって）","sentence_parts":["夏休み最初の日曜日","、遊園地は大変な混雑だった。"]},
    {"id":30,"level":"N1","grammar_display":"〜こととて","grammar_answer":"こととて","connection":"普通形（ナ形容詞・名詞 + のこととて）","sentence_parts":["急な","、何もご用意できませんでした。"]},
    {"id":31,"level":"N1","grammar_display":"〜ことだし","grammar_answer":"ことだし","connection":"普通形（ナ形容詞・名詞 + のことだし）","sentence_parts":["雨も降ってきた","、今日はこの辺でやめにしよう。"]},
    {"id":32,"level":"N1","grammar_display":"〜こともあって","grammar_answer":"こともあって","connection":"普通形（ナ形容詞な / 名詞の + こともあって）","sentence_parts":["彼は日本語が上手な","、すぐに日本の生活に慣れた。"]},
    {"id":33,"level":"N1","grammar_display":"〜ゆえに","grammar_answer":"ゆえに","connection":"普通形（ナ形容詞・名詞 + （である） + ゆえに）","sentence_parts":["若さ","、間違いを犯すこともあるだろう。"]},
    {"id":34,"level":"N1","grammar_display":"〜からこそ / 〜ばこそ","grammar_answer":"からこそ","connection":"普通形 + からこそ","sentence_parts":["あなたのことを思う","、厳しく言うのです。"]},
    {"id":35,"level":"N1","grammar_display":"〜ではあるまいし","grammar_answer":"ではあるまいし","connection":"名詞 + ではあるまいし","sentence_parts":["子供","、そんなことで泣くのはやめなさい。"]},
    {"id":36,"level":"N1","grammar_display":"〜始末だ","grammar_answer":"始末だ","connection":"動詞の辞書形 + 始末だ","sentence_parts":["彼は借金を重ね、ついには家を売る","。"]},
    {"id":37,"level":"N1","grammar_display":"〜た手前","grammar_answer":"手前","connection":"動詞た形 + 手前","sentence_parts":["「手伝う」と言った","、断るわけにはいかない。"]},
    {"id":38,"level":"N1","grammar_display":"〜はずみに","grammar_answer":"はずみに","connection":"動詞た形 / 名詞の + はずみに","sentence_parts":["くしゃみをした","、腰を痛めてしまった。"]},
    {"id":39,"level":"N1","grammar_display":"〜ずじまい","grammar_answer":"ずじまいだった","connection":"動詞ない形（ない→ず） + じまい","sentence_parts":["日本にいる間に、富士山に登ら","。"]},
    {"id":40,"level":"N2","grammar_display":"〜おかげで","grammar_answer":"おかげで","connection":"動詞/形容詞普通形 / 名詞の + おかげで","sentence_parts":["先生の","、試験に合格できました。"]},
    {"id":41,"level":"N2","grammar_display":"〜せいで","grammar_answer":"せいで","connection":"動詞/形容詞普通形 / 名詞の + せいで","sentence_parts":["事故の","、電車が遅れてしまった。"]},
    {"id":42,"level":"N2","grammar_display":"〜せいか","grammar_answer":"せいか","connection":"動詞/形容詞普通形 / 名詞の + せいか","sentence_parts":["気の","、最近彼が冷たい。"]},
    {"id":43,"level":"N2","grammar_display":"〜ために","grammar_answer":"ために","connection":"動詞/形容詞普通形 / 名詞の + ために","sentence_parts":["大雪の","、飛行機が欠航になった。"]},
    {"id":44,"level":"N2","grammar_display":"〜だけに","grammar_answer":"だけに","connection":"動詞/形容詞普通形 / 名詞 + だけに","sentence_parts":["期待が大きかった","、がっかりした。"]},
    {"id":45,"level":"N2","grammar_display":"〜だけあって","grammar_answer":"だけあって","connection":"動詞/形容詞普通形 / 名詞 + だけあって","sentence_parts":["さすがに一流ホテル","、サービスが素晴らしい。"]},
    {"id":46,"level":"N2","grammar_display":"〜ばかりに","grammar_answer":"ばかりに","connection":"動詞/形容詞普通形 / 名詞の + ばかりに","sentence_parts":["ちょっとした油断をした","、大事故になってしまった。"]},
    {"id":47,"level":"N2","grammar_display":"〜ことから","grammar_answer":"ことから","connection":"動詞/形容詞普通形 / 名詞の + ことから","sentence_parts":["富士山が見える","、この町は「富士見町」と名付けられた。"]},
    {"id":48,"level":"N2","grammar_display":"〜ところから","grammar_answer":"ところから","connection":"動詞/形容詞普通形 + ところから","sentence_parts":["彼の話し方","、彼が正直な人だとわかった。"]},
    {"id":49,"level":"N2","grammar_display":"〜ことだから","grammar_answer":"ことだから","connection":"名詞の + ことだから","sentence_parts":["真面目な田中さんの","、きっと時間通りに来るでしょう。"]},
    {"id":50,"level":"N2","grammar_display":"〜もの（もん）","grammar_answer":"もの","connection":"普通形 + もの / もん","sentence_parts":["だって、知らなかったんだ","。"]},
    {"id":51,"level":"N2","grammar_display":"〜ものだから","grammar_answer":"ものだから","connection":"普通形 + ものだから","sentence_parts":["事故があった","、遅刻してしまいました。"]},
    {"id":52,"level":"N2","grammar_display":"〜につき","grammar_answer":"につき","connection":"名詞 + につき","sentence_parts":["店内改装","、しばらく休業いたします。"]},
    {"id":53,"level":"N2","grammar_display":"〜以上は","grammar_answer":"以上は","connection":"動詞普通形 + 以上は","sentence_parts":["約束した","、守らなければならない。"]},
    {"id":54,"level":"N2","grammar_display":"〜うえは","grammar_answer":"うえは","connection":"動詞普通形 + うえは","sentence_parts":["こうなった","、覚悟を決めるしかない。"]},
    {"id":55,"level":"N2","grammar_display":"〜からには","grammar_answer":"からには","connection":"動詞普通形 + からには","sentence_parts":["日本に来た","、日本語をマスターしたい。"]},
    {"id":56,"level":"N2","grammar_display":"〜あまり","grammar_answer":"あまり","connection":"動詞辞書形 / 名詞の + あまり","sentence_parts":["嬉しさの","、涙が出てきた。"]},
    {"id":57,"level":"N2","grammar_display":"〜あまりの～に","grammar_answer":"あまりの暑さに","connection":"あまりの + 名詞 + に / で","sentence_parts":["","、食欲がなくなった。"]},
    {"id":58,"level":"N2","grammar_display":"〜あげく","grammar_answer":"あげく","connection":"動詞た形 / 名詞の + あげく","sentence_parts":["さんざん悩んだ","、結局何も決められなかった。"]},
    {"id":59,"level":"N2","grammar_display":"〜末に","grammar_answer":"末に","connection":"動詞た形 / 名詞の + 末に","sentence_parts":["長い議論の","、やっと結論が出た。"]},
    {"id":60,"level":"N1","grammar_display":"〜によるところが大きい","grammar_answer":"によるところが大きい","connection":"普通形（ナ形容詞な / 名詞の + こと）","sentence_parts":["今回の成功は、チーム全員の協力","。"]},
    // 3. 逆接・対比
    {"id":61,"level":"N1","grammar_display":"〜には〜が","grammar_answer":"には読んだが","connection":"動詞辞書形 + には + 動詞辞書形 + が","sentence_parts":["この本は読む","、内容はほとんど覚えていない。"]},
    {"id":62,"level":"N1","grammar_display":"〜とはいえ","grammar_answer":"とはいえ","connection":"普通形（ナ形容詞・名詞 + とはいえ）","sentence_parts":["まだ四月","、暖かい日が続いている。"]},
    {"id":63,"level":"N1","grammar_display":"〜といえども","grammar_answer":"といえども","connection":"普通形（ナ形容詞・名詞 + といえども）","sentence_parts":["専門家","、間違うことはある。"]},
    {"id":64,"level":"N1","grammar_display":"〜であれ","grammar_answer":"であれ","connection":"名詞 + であれ","sentence_parts":["たとえ国王","、法を破ることは許されない。"]},
    {"id":65,"level":"N1","grammar_display":"〜ものを","grammar_answer":"ものを","connection":"普通形 + ものを","sentence_parts":["もう少し頑張れば合格できた","、途中で諦めてしまった。"]},
    {"id":66,"level":"N1","grammar_display":"〜ないまでも","grammar_answer":"ないまでも","connection":"動詞ない形 + までも","sentence_parts":["優勝でき","、ベスト４には入りたい。"]},
    {"id":67,"level":"N1","grammar_display":"〜ならまだしも","grammar_answer":"ならまだしも","connection":"名詞 + ならまだしも","sentence_parts":["子供","、大人がそんなことをするのは許せない。"]},
    {"id":68,"level":"N1","grammar_display":"〜たら〜たで","grammar_answer":"たら広かったで","connection":"動詞た形 / 形容詞かった形 + ら + 同じ動詞/形容詞 + で","sentence_parts":["家は広かっ","、掃除が大変だ。"]},
    {"id":69,"level":"N1","grammar_display":"〜そうかと言って〜ない","grammar_answer":"そうかと言って","connection":"普通形 + そうかと言って + 否定形","sentence_parts":["この仕事は楽ではなさそうだが、","、できないわけではない。"]},
    {"id":70,"level":"N1","grammar_display":"〜に引き換え","grammar_answer":"に引き換え","connection":"名詞 + に引き換え","sentence_parts":["兄が倹約家なの","、弟は浪費家だ。"]},
    {"id":71,"level":"N1","grammar_display":"〜をよそに","grammar_answer":"をよそに","connection":"名詞 + をよそに","sentence_parts":["住民の心配","、ダムの建設計画が進められている。"]},
    {"id":72,"level":"N1","grammar_display":"〜をしりめに","grammar_answer":"をしりめに","connection":"名詞 + をしりめに","sentence_parts":["彼は親の反対","、家を出てしまった。"]},
    {"id":73,"level":"N1","grammar_display":"〜をものともせずに","grammar_answer":"をものともせずに","connection":"名詞 + をものともせずに","sentence_parts":["彼は体の障害","、明るく生きている。"]},
    {"id":74,"level":"N2","grammar_display":"〜といっても","grammar_answer":"といっても","connection":"普通形 + といっても","sentence_parts":["料理ができる","、簡単なものだけです。"]},
    {"id":75,"level":"N2","grammar_display":"〜からといって","grammar_answer":"からといって","connection":"普通形 + からといって + 否定形","sentence_parts":["日本人だ","、誰もが敬語を正しく使えるわけではない。"]},
    {"id":76,"level":"N2","grammar_display":"〜ながら","grammar_answer":"ながら","connection":"動詞ます形 / 形容詞 / 名詞 + ながら","sentence_parts":["残念","、ご期待には応えられません。"]},
    {"id":77,"level":"N2","grammar_display":"〜つつ（も）","grammar_answer":"つつも","connection":"動詞ます形 + つつ（も）","sentence_parts":["悪いと知り","、嘘をついてしまった。"]},
    {"id":78,"level":"N2","grammar_display":"〜ものの","grammar_answer":"ものの","connection":"動詞/形容詞普通形 + ものの","sentence_parts":["大学は卒業した","、就職先が見つからない。"]},
    {"id":79,"level":"N2","grammar_display":"〜にもかかわらず","grammar_answer":"にもかかわらず","connection":"動詞/形容詞普通形 / 名詞 + にもかかわらず","sentence_parts":["雨","、多くの人が集まった。"]},
    {"id":80,"level":"N2","grammar_display":"〜たところが","grammar_answer":"ところが","connection":"動詞た形 + ところが","sentence_parts":["薬を飲んだ","、少しも良くならなかった。"]},
    {"id":81,"level":"N2","grammar_display":"〜たところで","grammar_answer":"たところで","connection":"動詞た形 + ところで","sentence_parts":["今から謝っ","、許してもらえないだろう。"]},
    {"id":82,"level":"N2","grammar_display":"〜くせに","grammar_answer":"くせに","connection":"動詞/形容詞普通形 / 名詞の + くせに","sentence_parts":["知らない","、知っているふりをするな。"]},
    {"id":83,"level":"N2","grammar_display":"〜わりに（は）","grammar_answer":"わりには","connection":"動詞/形容詞普通形 / 名詞の + わりに（は）","sentence_parts":["年の","若く見える。"]},
    {"id":84,"level":"N2","grammar_display":"〜にしては","grammar_answer":"にしては","connection":"普通形（ナ形容詞・名詞 + にしては）","sentence_parts":["初めて","、上手にできましたね。"]},
    {"id":85,"level":"N2","grammar_display":"〜反面・半面","grammar_answer":"反面","connection":"動詞/形容詞普通形 / 名詞の + 反面/半面","sentence_parts":["都会の生活は便利な","、ストレスも多い。"]},
    {"id":86,"level":"N2","grammar_display":"〜かわりに","grammar_answer":"かわりに","connection":"動詞/形容詞普通形 / 名詞の + かわりに","sentence_parts":["音楽会に行く","、CDを一枚買える。"]},
    // 4. 仮定・条件
    {"id":87,"level":"N1","grammar_display":"〜ものなら","grammar_answer":"ものなら","connection":"動詞の可能形 + ものなら","sentence_parts":["昔に戻れる","、もう一度学生時代を過ごしたい。"]},
    {"id":88,"level":"N1","grammar_display":"〜ものとして","grammar_answer":"ものとして","connection":"普通形（ナ形容詞な / 名詞の + ものとして）","sentence_parts":["彼は会議に来ない","、話を進めましょう。"]},
    {"id":89,"level":"N1","grammar_display":"〜とあれば","grammar_answer":"とあれば","connection":"普通形（ナ形容詞・名詞 + とあれば）","sentence_parts":["子供のため","、どんなことでも我慢できる。"]},
    {"id":90,"level":"N1","grammar_display":"〜としたって","grammar_answer":"としたって","connection":"普通形（ナ形容詞・名詞 + としたって）","sentence_parts":["彼","、わざとやったわけではないだろう。"]},
    {"id":91,"level":"N1","grammar_display":"〜としたところで","grammar_answer":"としたところで","connection":"普通形（ナ形容詞・名詞 + としたところで）","sentence_parts":["今から急いだ","、もう間に合わないだろう。"]},
    {"id":92,"level":"N1","grammar_display":"〜たが・ら最後","grammar_answer":"たら最後","connection":"動詞た形 + が最後 / たら最後","sentence_parts":["彼は一度寝","、朝まで起きない。"]},
    {"id":93,"level":"N1","grammar_display":"〜ともなると","grammar_answer":"ともなると","connection":"名詞 + ともなると / ともなれば","sentence_parts":["大学生","、自分の行動に責任を持たなければならない。"]},
    {"id":94,"level":"N1","grammar_display":"〜ようと(が)〜ようと(が)","grammar_answer":"と雪が降ろうと","connection":"動詞の意向形 + と(が) + 動詞の意向形 + と(が)","sentence_parts":["雨が降ろう","、毎日散歩に出かける。"]},
    {"id":95,"level":"N2","grammar_display":"〜たとえ～ても","grammar_answer":"ても","connection":"たとえ + 動詞て形 / 形容詞くて形 / 名詞で + も","sentence_parts":["たとえ反対され","、自分の意見を主張するつもりだ。"]},
    {"id":96,"level":"N2","grammar_display":"〜としても","grammar_answer":"としても","connection":"普通形 + としても","sentence_parts":["もしそれが事実だ","、私は信じない。"]},
    {"id":97,"level":"N2","grammar_display":"〜にしても","grammar_answer":"にしても","connection":"普通形 + にしても","sentence_parts":["行く","行かないにしても、早く決めてください。"]},
    {"id":98,"level":"N2","grammar_display":"〜にしろ・～にせよ","grammar_answer":"にせよ","connection":"普通形 + にしろ / にせよ","sentence_parts":["来る","来ないにせよ、連絡してください。"]},
    {"id":99,"level":"N2","grammar_display":"〜としたら","grammar_answer":"としたら","connection":"普通形 + としたら / とすれば / とすると","sentence_parts":["もし宝くじが当たった","、何をしますか。"]},
    {"id":100,"level":"N2","grammar_display":"〜にしたら","grammar_answer":"にすれば","connection":"名詞 + にしたら / にすれば","sentence_parts":["私の立場","、その提案は受け入れられません。"]},
    {"id":101,"level":"N2","grammar_display":"〜（よ）うものなら","grammar_answer":"うものなら","connection":"動詞の意向形 + ものなら","sentence_parts":["先生にそんなことを言よ","、大変なことになる。"]},
    {"id":102,"level":"N2","grammar_display":"〜てからでないと","grammar_answer":"てからでないと","connection":"動詞て形 + からでないと","sentence_parts":["宿題をし","、遊びに行けません。"]},
    {"id":103,"level":"N2","grammar_display":"〜ないことには","grammar_answer":"ないことには","connection":"動詞ない形 + ことには","sentence_parts":["実際に会ってみ","、どんな人かわからない。"]},
    {"id":104,"level":"N2","grammar_display":"〜なしには","grammar_answer":"なしには","connection":"名詞 + なしには / なくしては","sentence_parts":["皆さんの協力","、このプロジェクトは成功しなかっただろう。"]},
    {"id":105,"level":"N2","grammar_display":"〜さえ～ば","grammar_answer":"さえあれば","connection":"名詞 + さえ + 動詞ば形","sentence_parts":["お金","、何でもできると思うのは間違いだ。"]},
    {"id":106,"level":"N2","grammar_display":"〜限り","grammar_answer":"限り","connection":"動詞の辞書形/ない形/ている形 + 限り","sentence_parts":["私が知っている","、彼は正直な人です。"]},
    {"id":107,"level":"N1","grammar_display":"〜ばそれまでだ","grammar_answer":"ばそれまでだ","connection":"動詞ば形 + それまでだ","sentence_parts":["どんなに高価なものでも、壊れてしまえ","。"]},
    // 5. 対象・関連・基準
    {"id":108,"level":"N1","grammar_display":"〜がてら","grammar_answer":"がてら","connection":"動詞ます形 / 名詞 + がてら","sentence_parts":["散歩","、コンビニに寄ってきた。"]},
    {"id":109,"level":"N1","grammar_display":"〜かたがた","grammar_answer":"かたがた","connection":"名詞 + かたがた","sentence_parts":["お礼","、ご挨拶に伺いました。"]},
    {"id":110,"level":"N1","grammar_display":"〜かたわら","grammar_answer":"かたわら","connection":"動詞辞書形 / 名詞の + かたわら","sentence_parts":["彼は会社員として働く","、小説を書いている。"]},
    {"id":111,"level":"N1","grammar_display":"〜に即して","grammar_answer":"に即して","connection":"名詞 + に即して","sentence_parts":["事実","、報告書を作成してください。"]},
    {"id":112,"level":"N1","grammar_display":"〜に関わる","grammar_answer":"に関わる","connection":"名詞 + に関わる","sentence_parts":["それは人の命","問題だ。"]},
    {"id":113,"level":"N1","grammar_display":"〜に関わりなく","grammar_answer":"に関わりなく","connection":"名詞 + に関わりなく","sentence_parts":["経験の有無","、やる気のある人を募集します。"]},
    {"id":114,"level":"N1","grammar_display":"〜にかけては","grammar_answer":"にかけては","connection":"名詞 + にかけては","sentence_parts":["足の速さ","、彼は誰にも負けない。"]},
    {"id":115,"level":"N1","grammar_display":"〜と相まって","grammar_answer":"と相まって","connection":"名詞 + と相まって","sentence_parts":["彼の才能が努力","、素晴らしい成果を生んだ。"]},
    {"id":116,"level":"N1","grammar_display":"〜にもまして","grammar_answer":"にもまして","connection":"名詞 / 動詞こと + にもまして","sentence_parts":["去年","、今年は暑い。"]},
    {"id":117,"level":"N1","grammar_display":"〜をもって","grammar_answer":"をもちまして","connection":"名詞 + をもって","sentence_parts":["本日","、閉店させていただきます。"]},
    {"id":118,"level":"N1","grammar_display":"〜を控えて","grammar_answer":"を控えて","connection":"名詞 + を控えて","sentence_parts":["卒業","、学生たちは少し寂しそうだ。"]},
    {"id":119,"level":"N1","grammar_display":"〜あっての","grammar_answer":"あっての","connection":"名詞 + あっての + 名詞","sentence_parts":["お客様","商売です。"]},
    {"id":120,"level":"N1","grammar_display":"〜いかんだ","grammar_answer":"いかんだ","connection":"名詞（の） + いかんだ / いかんによって","sentence_parts":["試験の結果","、卒業できないかもしれない。"]},
    {"id":121,"level":"N1","grammar_display":"〜いかんによらず","grammar_answer":"いかんによらず","connection":"名詞（の） + いかんによらず","sentence_parts":["理由の","、遅刻は認められません。"]},
    {"id":122,"level":"N2","grammar_display":"〜ついでに","grammar_answer":"ついでに","connection":"動詞の辞書形/た形 / 名詞の + ついでに","sentence_parts":["買い物に行く","、手紙を出してきた。"]},
    {"id":123,"level":"N2","grammar_display":"〜うえで","grammar_answer":"うえで","connection":"動詞のた形 / 名詞の + うえで","sentence_parts":["よく考えた","、ご返事します。"]},
    {"id":124,"level":"N2","grammar_display":"〜において","grammar_answer":"において","connection":"名詞 + において","sentence_parts":["現代社会","、コンピューターは不可欠なものである。"]},
    {"id":125,"level":"N2","grammar_display":"〜における","grammar_answer":"における","connection":"名詞 + における","sentence_parts":["現代社会","生活には、多くのストレスが伴う。"]},
    {"id":126,"level":"N2","grammar_display":"〜に関して","grammar_answer":"に関して","connection":"名詞 + に関して","sentence_parts":["この問題","、ご意見がありますか。"]},
    {"id":127,"level":"N2","grammar_display":"〜について","grammar_answer":"について","connection":"名詞 + について","sentence_parts":["日本の文化","、もっと知りたいです。"]},
    {"id":128,"level":"N2","grammar_display":"〜に対して","grammar_answer":"に対して","connection":"名詞 + に対して","sentence_parts":["先生の質問","、誰も答えられなかった。"]},
    {"id":129,"level":"N2","grammar_display":"〜に比べて","grammar_answer":"に比べて","connection":"名詞 + に比べて","sentence_parts":["今年は去年","、雨が多い。"]},
    {"id":130,"level":"N2","grammar_display":"〜にとって","grammar_answer":"にとって","connection":"名詞 + にとって","sentence_parts":["私","、これは忘れられない思い出です。"]},
    {"id":131,"level":"N2","grammar_display":"〜によって","grammar_answer":"によって","connection":"名詞 + によって","sentence_parts":["台風","、家が壊れてしまった。"]},
    {"id":132,"level":"N2","grammar_display":"〜によっては","grammar_answer":"によっては","connection":"名詞 + によっては","sentence_parts":["国","、習慣が違う。"]},
    {"id":133,"level":"N2","grammar_display":"〜に基づいて","grammar_answer":"に基づいて","connection":"名詞 + に基づいて","sentence_parts":["事実","、判断してください。"]},
    {"id":134,"level":"N2","grammar_display":"〜をもとに（して）","grammar_answer":"をもとにして","connection":"名詞 + をもとに（して）","sentence_parts":["この小説は、歴史的な事実","書かれている。"]},
    {"id":135,"level":"N2","grammar_display":"〜のもとで","grammar_answer":"のもとで","connection":"名詞 + のもとで / のもとに","sentence_parts":["厳しい先生","、私たちは成長した。"]},
    {"id":136,"level":"N2","grammar_display":"〜上で","grammar_answer":"上で","connection":"名詞 + 上で","sentence_parts":["法律","、それは許されない。"]},
    {"id":137,"level":"N2","grammar_display":"〜上","grammar_answer":"上","connection":"名詞 + 上","sentence_parts":["健康","の問題で、旅行を中止した。"]},
    {"id":138,"level":"N2","grammar_display":"〜をめぐって","grammar_answer":"をめぐって","connection":"名詞 + をめぐって / をめぐる","sentence_parts":["遺産","、兄弟が争っている。"]},
    {"id":139,"level":"N2","grammar_display":"〜にわたって","grammar_answer":"にわたって","connection":"名詞 + にわたって","sentence_parts":["会議は５日間","行われた。"]},
    {"id":140,"level":"N2","grammar_display":"〜を通じて","grammar_answer":"を通じて","connection":"名詞 + を通じて / を通して","sentence_parts":["彼とは共通の友人","知り合った。"]},
    {"id":141,"level":"N2","grammar_display":"〜から〜にかけて","grammar_answer":"から今朝にかけて","connection":"名詞 + から + 名詞 + にかけて","sentence_parts":["昨夜","、大雨が降った。"]},
    {"id":142,"level":"N2","grammar_display":"〜にかわって","grammar_answer":"にかわって","connection":"名詞 + にかわって","sentence_parts":["父","、私がご挨拶いたします。"]},
    {"id":143,"level":"N2","grammar_display":"〜をはじめ（として）","grammar_answer":"をはじめ","connection":"名詞 + をはじめ（として）","sentence_parts":["校長先生","、多くの先生方が出席された。"]},
    {"id":144,"level":"N2","grammar_display":"〜とおり","grammar_answer":"とおりに","connection":"動詞の辞書形/た形 / 名詞の + とおり","sentence_parts":["私が言う","、やってください。"]},
    {"id":145,"level":"N2","grammar_display":"〜に応じて","grammar_answer":"に応じて","connection":"名詞 + に応じて","sentence_parts":["能力","、給料を決めます。"]},
    {"id":146,"level":"N2","grammar_display":"〜にこたえて","grammar_answer":"にこたえて","connection":"名詞 + にこたえて","sentence_parts":["国民の期待","、新しい政策が打ち出された。"]},
    {"id":147,"level":"N2","grammar_display":"〜に反して","grammar_answer":"に反して","connection":"名詞 + に反して","sentence_parts":["予想","、試験はとても簡単だった。"]},
    {"id":148,"level":"N2","grammar_display":"〜に加えて","grammar_answer":"に加えて","connection":"名詞 + に加えて","sentence_parts":["雨","、風も強くなってきた。"]},
    {"id":149,"level":"N2","grammar_display":"〜に沿って","grammar_answer":"に沿って","connection":"名詞 + に沿って","sentence_parts":["計画","、作業を進めてください。"]},
    {"id":150,"level":"N2","grammar_display":"〜に従って","grammar_answer":"に従って","connection":"名詞 + に従って","sentence_parts":["指示","、行動してください。"]},
    {"id":151,"level":"N2","grammar_display":"〜につれて","grammar_answer":"につれて","connection":"動詞の辞書形 / 名詞 + につれて","sentence_parts":["年をとる","、体力がなくなってきた。"]},
    {"id":152,"level":"N2","grammar_display":"〜に伴って","grammar_answer":"に伴って","connection":"動詞の辞書形 / 名詞 + に伴って","sentence_parts":["経済の発展","、環境問題が深刻化している。"]},
    {"id":153,"level":"N2","grammar_display":"〜とともに","grammar_answer":"とともに","connection":"動詞の辞書形 / 名詞 + とともに","sentence_parts":["家族","、日本へ来た。"]},
    {"id":154,"level":"N2","grammar_display":"〜にかかわらず","grammar_answer":"にかかわらず","connection":"動詞の辞書形/ない形 / 名詞 + にかかわらず","sentence_parts":["天候","、試合は行われます。"]},
    {"id":155,"level":"N2","grammar_display":"〜を問わず","grammar_answer":"を問わず","connection":"名詞 + を問わず","sentence_parts":["年齢","、誰でも参加できます。"]},
    // 6. 強調・限定
    {"id":156,"level":"N1","grammar_display":"〜はおろか","grammar_answer":"はおろか","connection":"名詞 + はおろか","sentence_parts":["彼は漢字","、ひらがなも書けない。"]},
    {"id":157,"level":"N1","grammar_display":"〜もさることながら","grammar_answer":"もさることながら","connection":"名詞 + もさることながら","sentence_parts":["このレストランは味","、サービスも素晴らしい。"]},
    {"id":158,"level":"N1","grammar_display":"〜言うに及ばず","grammar_answer":"は言うに及ばず","connection":"名詞 + は言うに及ばず","sentence_parts":["国内","、海外でも人気がある。"]},
    {"id":159,"level":"N1","grammar_display":"〜ならではの","grammar_answer":"ならではの","connection":"名詞 + ならではの","sentence_parts":["これは京都","景色だ。"]},
    {"id":160,"level":"N1","grammar_display":"〜ともあろう","grammar_answer":"ともあろう","connection":"名詞 + ともあろう + 名詞","sentence_parts":["大学の教授","人が、そんなことをするなんて信じられない。"]},
    {"id":161,"level":"N1","grammar_display":"〜に至って","grammar_answer":"に至って","connection":"名詞 / 動詞辞書形 + に至って","sentence_parts":["事ここに及ぶ","、ようやく彼は自分の過ちを認めた。"]},
    {"id":162,"level":"N1","grammar_display":"〜にして","grammar_answer":"にして","connection":"名詞 + にして","sentence_parts":["彼は学者","、偉大な芸術家でもあった。"]},
    {"id":163,"level":"N1","grammar_display":"〜に〜を重ねる","grammar_answer":"に研究を重ね","connection":"名詞 + に + 名詞 + を重ねる","sentence_parts":["彼は研究","、ついに大発見をした。"]},
    {"id":164,"level":"N1","grammar_display":"〜をおいて〜ない","grammar_answer":"をおいて","connection":"名詞 + をおいて + ほかに～ない","sentence_parts":["この仕事を任せられるのは、君","ほかにいない。"]},
    {"id":165,"level":"N1","grammar_display":"〜てやまない","grammar_answer":"てやまない","connection":"動詞て形 + やまない","sentence_parts":["卒業生の皆さんの成功を願っ","。"]},
    {"id":166,"level":"N1","grammar_display":"〜たりとも","grammar_answer":"たりとも","connection":"数量詞 + たりとも + 否定形","sentence_parts":["一円","無駄にはできない。"]},
    {"id":167,"level":"N1","grammar_display":"〜てまで","grammar_answer":"てまで","connection":"動詞て形 + まで","sentence_parts":["親に嘘をつい","、遊びに行きたいとは思わない。"]},
    {"id":168,"level":"N1","grammar_display":"〜からある","grammar_answer":"からある","connection":"数量詞 + からある","sentence_parts":["10キロ","荷物を一人で運んだ。"]},
    {"id":169,"level":"N1","grammar_display":"〜だに","grammar_answer":"だに","connection":"名詞 / 動詞辞書形 + だに","sentence_parts":["その事故のことは思い出す","恐ろしい。"]},
    {"id":170,"level":"N1","grammar_display":"〜すら","grammar_answer":"すら","connection":"名詞 + すら / ですら","sentence_parts":["子供","知っていることを、大人の彼が知らないはずがない。"]},
    {"id":171,"level":"N1","grammar_display":"〜だけ","grammar_answer":"だけ","connection":"動詞の可能形/たい形 + だけ","sentence_parts":["食べたい","食べていいですよ。"]},
    {"id":172,"level":"N1","grammar_display":"ただ〜のみ","grammar_answer":"のみだ","connection":"ただ + 動詞辞書形 / 名詞 + のみ","sentence_parts":["今はただ、成功を祈る","。"]},
    {"id":173,"level":"N2","grammar_display":"〜こそ","grammar_answer":"こそ","connection":"名詞 / て形 + こそ","sentence_parts":["あなた","、この仕事にふさわしい人だ。"]},
    {"id":174,"level":"N2","grammar_display":"〜さえ","grammar_answer":"さえ","connection":"名詞 + さえ","sentence_parts":["ひらがな","書けないなんて、信じられない。"]},
    {"id":175,"level":"N2","grammar_display":"〜限りでは","grammar_answer":"限りでは","connection":"動詞の辞書形/た形 + 限りでは","sentence_parts":["私が見た","、彼が犯人ではありません。"]},
    {"id":176,"level":"N2","grammar_display":"〜に限って","grammar_answer":"に限って","connection":"名詞 + に限って","sentence_parts":["うちの子","、そんな悪いことをするはずがない。"]},
    {"id":177,"level":"N2","grammar_display":"〜に限り","grammar_answer":"に限り","connection":"名詞 + に限り","sentence_parts":["本日","、全品10％割引です。"]},
    {"id":178,"level":"N2","grammar_display":"〜に限る","grammar_answer":"に限る","connection":"動詞の辞書形 / 名詞 + に限る","sentence_parts":["疲れた時は、温泉に入るの","。"]},
    {"id":179,"level":"N2","grammar_display":"〜に限らず","grammar_answer":"に限らず","connection":"名詞 + に限らず","sentence_parts":["このアニメは子供","、大人にも人気がある。"]},
    {"id":180,"level":"N2","grammar_display":"〜とは限らない","grammar_answer":"とは限らない","connection":"普通形 + とは限らない","sentence_parts":["お金持ちが必ずしも幸せだ","。"]},
    {"id":181,"level":"N2","grammar_display":"〜にとどまらない","grammar_answer":"にとどまらず","connection":"名詞 / 動詞の辞書形 + にとどまらない","sentence_parts":["その影響は国内","、海外にも及んだ。"]},
    {"id":182,"level":"N2","grammar_display":"〜のみならず","grammar_answer":"のみならず","connection":"普通形（ナ形容詞・名詞 + である） + のみならず","sentence_parts":["彼は学者として","、政治家としても活躍した。"]},
    {"id":183,"level":"N2","grammar_display":"〜ばかりでなく","grammar_answer":"ばかりでなく","connection":"普通形（ナ形容詞な / 名詞の） + ばかりでなく","sentence_parts":["彼女は英語","、フランス語も話せる。"]},
    {"id":184,"level":"N2","grammar_display":"〜ばかりか","grammar_answer":"ばかりか","connection":"普通形（ナ形容詞な / 名詞） + ばかりか","sentence_parts":["彼は漢字が読めない","、ひらがなさえ書けない。"]},
    {"id":185,"level":"N2","grammar_display":"〜どころか","grammar_answer":"どころか","connection":"普通形（ナ形容詞な / 名詞の） + どころか","sentence_parts":["勉強する","、毎日遊んでばかりいる。"]},
    {"id":186,"level":"N2","grammar_display":"〜どころではない","grammar_answer":"どころではない","connection":"動詞の辞書形 / 名詞 + どころではない","sentence_parts":["忙しくて、食事をする","。"]},
    {"id":187,"level":"N2","grammar_display":"〜上に","grammar_answer":"上に","connection":"普通形（ナ形容詞な / 名詞の） + 上に","sentence_parts":["この料理は美味しい","、値段も安い。"]},
    {"id":188,"level":"N2","grammar_display":"〜ことか","grammar_answer":"ことか","connection":"動詞/形容詞普通形 + ことか","sentence_parts":["合格できたら、どんなに嬉しい","。"]},
    {"id":189,"level":"N2","grammar_display":"〜はもちろん","grammar_answer":"はもちろん","connection":"名詞 + はもちろん / はもとより","sentence_parts":["彼は英語","、中国語も話せる。"]},
    {"id":190,"level":"N2","grammar_display":"〜はしない","grammar_answer":"はしない","connection":"動詞ます形 + はしない / もしない","sentence_parts":["あんなところへ二度と行くもの","。"]},
    {"id":191,"level":"N2","grammar_display":"〜っこない","grammar_answer":"っこない","connection":"動詞ます形 + っこない","sentence_parts":["一日でこの仕事を全部終わらせるなんて、でき","。"]},
    {"id":192,"level":"N2","grammar_display":"〜からして","grammar_answer":"からして","connection":"名詞 + からして","sentence_parts":["彼の服装","、普通の人とは違う。"]},
    {"id":193,"level":"N2","grammar_display":"〜抜きで","grammar_answer":"抜きで","connection":"名詞 + 抜きで / 抜きにして","sentence_parts":["冗談","、真面目な話をしましょう。"]},
    {"id":194,"level":"N2","grammar_display":"〜にほかならない","grammar_answer":"にほかならない","connection":"名詞 + にほかならない","sentence_parts":["この成功は、皆さんの努力の結果","。"]},
    {"id":195,"level":"N2","grammar_display":"〜でなくてなんだろう","grammar_answer":"でなくてなんだろう","connection":"名詞 + でなくてなんだろう","sentence_parts":["これが愛","。"]},
    // 7. 並列・列挙
    {"id":196,"level":"N1","grammar_display":"〜かと思えば〜もいる","grammar_answer":"かと思えば","connection":"動詞/形容詞普通形 + かと思えば","sentence_parts":["このクラスには、よくしゃべる学生がいる","、ほとんど話さない学生もいる。"]},
    {"id":197,"level":"N1","grammar_display":"〜だの〜だの","grammar_answer":"だの、仕事が忙しすぎるだの","connection":"普通形 + だの + 普通形 + だの","sentence_parts":["彼は給料が安い","、文句ばかり言っている。"]},
    {"id":198,"level":"N1","grammar_display":"〜なり〜なり","grammar_answer":"なり、友達に相談するなり","connection":"動詞辞書形 / 名詞 + なり + 動詞辞書形 / 名詞 + なり","sentence_parts":["分からないことがあったら、先生に聞く","してください。"]},
    {"id":199,"level":"N1","grammar_display":"〜といい〜といい","grammar_answer":"といい、色といい","connection":"名詞 + といい + 名詞 + といい","sentence_parts":["このカバンは、デザイン","、とても気に入った。"]},
    {"id":200,"level":"N1","grammar_display":"〜であれ〜であれ","grammar_answer":"であれ雨天であれ","connection":"名詞 + であれ + 名詞 + であれ","sentence_parts":["晴天","、試合は予定通り行います。"]},
    {"id":201,"level":"N1","grammar_display":"〜つ〜つ","grammar_answer":"つ抜かれつ","connection":"動詞ます形（ます→つ） + 動詞ます形（ます→つ）","sentence_parts":["二人は抜き","のデッドヒートを繰り広げた。"]},
    {"id":202,"level":"N2","grammar_display":"〜やら～やら","grammar_answer":"やら本やら","connection":"名詞 / 動詞の辞書形 / 形容詞 + やら","sentence_parts":["机の上は、ノート","でいっぱいだ。"]},
    {"id":203,"level":"N2","grammar_display":"〜も～ば～も","grammar_answer":"もいれば、静かな人もいる","connection":"名詞 + も + 動詞ば形 + 名詞 + も","sentence_parts":["このクラスには、元気な人","。"]},
    {"id":204,"level":"N2","grammar_display":"〜につけ～につけ","grammar_answer":"につけ悪いにつけ","connection":"動詞の辞書形 / 形容詞 + につけ","sentence_parts":["良い","、彼はいつも報告してくる。"]},
    {"id":205,"level":"N2","grammar_display":"〜にしても～にしても","grammar_answer":"にしても行かないにしても","connection":"普通形 + にしても","sentence_parts":["行く","、早く決めてください。"]},
    // 8. 話題提出
    {"id":206,"level":"N1","grammar_display":"〜ときたら","grammar_answer":"ときたら","connection":"名詞 + ときたら","sentence_parts":["うちの猫","、一日中寝てばかりいる。"]},
    {"id":207,"level":"N1","grammar_display":"〜に至っては","grammar_answer":"に至っては","connection":"名詞 + に至っては","sentence_parts":["兄は怠け者で、弟","、全く働こうとしない。"]},
    {"id":208,"level":"N1","grammar_display":"〜たるもの","grammar_answer":"たるもの","connection":"名詞 + たるもの","sentence_parts":["教師","、学生の模範となるべきだ。"]},
    {"id":209,"level":"N1","grammar_display":"〜とは","grammar_answer":"とは","connection":"普通形 + とは","sentence_parts":["一人で山に登るなんて、無謀だ","このことだ。"]},
    {"id":210,"level":"N1","grammar_display":"〜はいざ知らず","grammar_answer":"はいざ知らず","connection":"名詞 + は（なら）いざ知らず","sentence_parts":["昔","、今はそんなことは通用しない。"]},
    {"id":211,"level":"N1","grammar_display":"〜はともあれ","grammar_answer":"はともあれ","connection":"名詞 + はともあれ","sentence_parts":["結果","、最後まで頑張ったことが大切だ。"]},
    {"id":212,"level":"N1","grammar_display":"〜はさておき","grammar_answer":"はさておき","connection":"名詞 + はさておき","sentence_parts":["冗談","、本題に入りましょう。"]},
    {"id":213,"level":"N2","grammar_display":"〜というと","grammar_answer":"というと","connection":"名詞 / 普通形 + というと / といえば / といったら","sentence_parts":["日本の花","、やはり桜でしょう。"]},
    {"id":214,"level":"N2","grammar_display":"〜といえば","grammar_answer":"といえば","connection":"名詞 / 普通形 + というと / といえば / といったら","sentence_parts":["田中さん","、最近見かけませんね。"]},
    {"id":215,"level":"N2","grammar_display":"〜といったら","grammar_answer":"といったら","connection":"名詞 / 普通形 + というと / といえば / といったら","sentence_parts":["その景色の美しさ","、言葉では表現できないほどだった。"]},
    {"id":216,"level":"N2","grammar_display":"〜かというと","grammar_answer":"かというと","connection":"普通形 + かというと / かといえば","sentence_parts":["なぜ彼が選ばれたの","、経験が豊富だからだ。"]},
    {"id":217,"level":"N2","grammar_display":"〜からいうと","grammar_answer":"からいえば","connection":"名詞 + からいうと / からいえば / からいって","sentence_parts":["品質の点","、この製品が一番だ。"]},
    {"id":218,"level":"N2","grammar_display":"〜からすると","grammar_answer":"からすれば","connection":"名詞 + からすると / からすれば","sentence_parts":["私の立場","、その意見には賛成できない。"]},
    {"id":219,"level":"N2","grammar_display":"〜から見ると","grammar_answer":"から見れば","connection":"名詞 + から見ると / から見れば / から見て","sentence_parts":["専門家","、その判断は間違っているかもしれない。"]},
    {"id":220,"level":"N2","grammar_display":"〜にしてみれば","grammar_answer":"にしてみれば","connection":"名詞 + にしてみれば","sentence_parts":["親","、子供の将来が心配なのだろう。"]},
    {"id":221,"level":"N2","grammar_display":"〜はともかく","grammar_answer":"はともかく","connection":"名詞 + はともかく","sentence_parts":["味","、値段が安いのが魅力だ。"]},
    {"id":222,"level":"N2","grammar_display":"〜ならともかく","grammar_answer":"ならともかく","connection":"名詞 + ならともかく","sentence_parts":["子供","、大人がそんなことをしてはいけない。"]},
    // 9. 判断・評価
    {"id":223,"level":"N1","grammar_display":"〜までもない","grammar_answer":"までもない","connection":"動詞辞書形 + までもない","sentence_parts":["言う","、これは彼の責任だ。"]},
    {"id":224,"level":"N1","grammar_display":"〜にあたらない","grammar_answer":"にあたらない","connection":"動詞辞書形 / 名詞 + にあたらない","sentence_parts":["彼の失敗を責める","。"]},
    {"id":225,"level":"N1","grammar_display":"〜にかたくない","grammar_answer":"にかたくない","connection":"名詞 / 動詞辞書形 + にかたくない","sentence_parts":["彼がどれほど苦労したか、想像","。"]},
    {"id":226,"level":"N1","grammar_display":"〜に限ったことではない","grammar_answer":"に限ったことではない","connection":"名詞 + に限ったことではない","sentence_parts":["若者の言葉遣いが乱れているのは、日本","。"]},
    {"id":227,"level":"N1","grammar_display":"〜ないとも限らない","grammar_answer":"ないとも限らない","connection":"動詞ない形 / 形容詞ない形 + とも限らない","sentence_parts":["絶対に勝てるとは言えない。負け","。"]},
    {"id":228,"level":"N1","grammar_display":"〜といったらない","grammar_answer":"といったらなかった","connection":"形容詞 + といったらない","sentence_parts":["今日の試験の難しさ","。"]},
    {"id":229,"level":"N1","grammar_display":"なんと〜だろう","grammar_answer":"なんてきれいなんだろう","connection":"なんと + 形容詞/副詞 + だろう","sentence_parts":["この景色は","。"]},
    {"id":230,"level":"N1","grammar_display":"〜くらいなら","grammar_answer":"くらいなら","connection":"動詞辞書形 + くらいなら","sentence_parts":["あんな人に頭を下げる","、会社を辞めた方がいい。"]},
    {"id":231,"level":"N1","grammar_display":"〜に越したことはない","grammar_answer":"に越したことはない","connection":"普通形（ナ形容詞・名詞 + に） + 越したことはない","sentence_parts":["用心する","。"]},
    {"id":232,"level":"N1","grammar_display":"〜ないものでもない","grammar_answer":"ないものでもない","connection":"動詞ない形 + ものでもない","sentence_parts":["条件によっては、引き受け","。"]},
    {"id":233,"level":"N1","grammar_display":"〜といって〜ない","grammar_answer":"といって","connection":"〜といって + 否定形","sentence_parts":["夏だ","、毎日暑いわけではない。"]},
    {"id":234,"level":"N1","grammar_display":"〜という〜ない","grammar_answer":"という学生は","connection":"〜という + 名詞 + はない","sentence_parts":["このクラスには、遅刻する","一人もいない。"]},
    {"id":235,"level":"N1","grammar_display":"〜までだ","grammar_answer":"までだ","connection":"動詞辞書形 / た形 + までだ","sentence_parts":["誰も協力してくれないなら、一人でやる","。"]},
    {"id":236,"level":"N1","grammar_display":"〜てしかるべきだ","grammar_answer":"てしかるべきだ","connection":"動詞て形 + しかるべきだ","sentence_parts":["彼は罪を犯したのだから、罰せられ","。"]},
    {"id":237,"level":"N1","grammar_display":"〜限りだ","grammar_answer":"限りだ","connection":"形容詞 + 限りだ","sentence_parts":["友人の結婚式に出席できて、嬉しい","。"]},
    {"id":238,"level":"N1","grammar_display":"〜極まる / 〜極まりない","grammar_answer":"極まりない","connection":"ナ形容詞語幹 + 極まる / 極まりない","sentence_parts":["彼の態度は失礼","。"]},
    {"id":239,"level":"N1","grammar_display":"〜の至り","grammar_answer":"の至り","connection":"名詞 + の至り","sentence_parts":["このような盛大な会にお招きいただき、光栄","です。"]},
    {"id":240,"level":"N1","grammar_display":"〜嫌いがある","grammar_answer":"きらいがある","connection":"動詞辞書形 / 名詞の + 嫌いがある","sentence_parts":["彼は物事を悲観的に考える","。"]},
    {"id":241,"level":"N1","grammar_display":"〜に足る","grammar_answer":"に足る","connection":"動詞辞書形 / 名詞 + に足る","sentence_parts":["彼の行動は尊敬","ものだ。"]},
    {"id":242,"level":"N1","grammar_display":"〜あるまじき","grammar_answer":"あるまじき","connection":"名詞 + にあるまじき + 名詞","sentence_parts":["それは教育者に","言動だ。"]},
    {"id":243,"level":"N1","grammar_display":"〜というところだ","grammar_answer":"というところだろう","connection":"数量詞 + というところだ","sentence_parts":["この仕事、今日中に終わるのはまあ、半分まで","。"]},
    {"id":244,"level":"N2","grammar_display":"〜はずだ","grammar_answer":"はずだ","connection":"普通形（ナ形容詞な / 名詞の） + はずだ","sentence_parts":["彼は昨日日本に来たのだから、まだ日本の生活に慣れていない","。"]},
    {"id":245,"level":"N2","grammar_display":"〜はずがない","grammar_answer":"はずがない","connection":"普通形（ナ形容詞な / 名詞の） + はずがない","sentence_parts":["あんなに真面目な彼が、嘘をつく","。"]},
    {"id":246,"level":"N2","grammar_display":"〜わけだ","grammar_answer":"わけだ","connection":"普通形（ナ形容詞な / 名詞の） + わけだ","sentence_parts":["暑い","。クーラーが壊れている。"]},
    {"id":247,"level":"N2","grammar_display":"〜わけがない","grammar_answer":"わけがない","connection":"普通形（ナ形容詞な / 名詞の） + わけがない","sentence_parts":["こんなに難しい問題、子供にできる","。"]},
    {"id":248,"level":"N2","grammar_display":"〜わけではない","grammar_answer":"わけではない","connection":"普通形 + わけではない","sentence_parts":["日本の料理が全部好きだという","。"]},
    {"id":249,"level":"N2","grammar_display":"〜というわけではない","grammar_answer":"というわけではない","connection":"普通形 + というわけではない","sentence_parts":["いつでも電話に出られる","ので、ご了承ください。"]},
    {"id":250,"level":"N2","grammar_display":"〜わけにはいかない","grammar_answer":"わけにはいかない","connection":"動詞の辞書形/ない形 + わけにはいかない","sentence_parts":["大事な会議があるので、休む","。"]},
    {"id":251,"level":"N2","grammar_display":"〜ものだ","grammar_answer":"ものだ","connection":"動詞の辞書形/ない形 / 形容詞 + ものだ","sentence_parts":["年を取れば、体力が衰える","。"]},
    {"id":252,"level":"N2","grammar_display":"〜ものではない","grammar_answer":"ものではない","connection":"動詞の辞書形 + ものではない","sentence_parts":["人の悪口を言う","。"]},
    {"id":253,"level":"N2","grammar_display":"〜というものだ","grammar_answer":"というものだ","connection":"普通形 + というものだ","sentence_parts":["困っている人を助けるのが、人間","。"]},
    {"id":254,"level":"N2","grammar_display":"〜というものではない","grammar_answer":"というものではない","connection":"普通形 + というものではない","sentence_parts":["お金があれば幸せになれる","。"]},
    {"id":255,"level":"N2","grammar_display":"〜ものか","grammar_answer":"ものか","connection":"普通形（ナ形容詞な / 名詞な） + ものか","sentence_parts":["あんな店、二度と行く","。"]},
    {"id":256,"level":"N2","grammar_display":"〜ものがある","grammar_answer":"ものがある","connection":"動詞の辞書形 / 形容詞 + ものがある","sentence_parts":["彼の演奏には、人を感動させる","。"]},
    {"id":257,"level":"N2","grammar_display":"〜べきだ","grammar_answer":"べきだ","connection":"動詞の辞書形 + べきだ","sentence_parts":["学生はもっと勉強する","。"]},
    {"id":258,"level":"N2","grammar_display":"〜ことだ","grammar_answer":"ことだ","connection":"動詞の辞書形/ない形 + ことだ","sentence_parts":["健康のためには、よく寝る","。"]},
    {"id":259,"level":"N2","grammar_display":"〜ことに（は）","grammar_answer":"ことに","connection":"動詞た形 / 形容詞 + ことに（は）","sentence_parts":["嬉しい","、試験に合格した。"]},
    {"id":260,"level":"N2","grammar_display":"〜ことはない","grammar_answer":"ことはない","connection":"動詞の辞書形 + ことはない","sentence_parts":["心配する","。きっと大丈夫だ。"]},
    {"id":261,"level":"N2","grammar_display":"〜ほど〜ない","grammar_answer":"ほど","connection":"名詞 + ほど + 否定形","sentence_parts":["今年の夏は去年","暑くない。"]},
    {"id":262,"level":"N2","grammar_display":"〜ほど〜はない","grammar_answer":"ほど","connection":"名詞 + ほど + 名詞 + はない","sentence_parts":["富士山","美しい山はない。"]},
    {"id":263,"level":"N2","grammar_display":"〜とみえる","grammar_answer":"とみえる","connection":"普通形 + とみえる","sentence_parts":["彼は疲れている","。顔色が悪い。"]},
    {"id":264,"level":"N2","grammar_display":"〜にすぎない","grammar_answer":"にすぎない","connection":"普通形（ナ形容詞・名詞 + である） + にすぎない","sentence_parts":["それはただの噂","。"]},
    {"id":265,"level":"N2","grammar_display":"〜に相違ない","grammar_answer":"に相違ない","connection":"普通形（ナ形容詞・名詞 + である） + に相違ない","sentence_parts":["彼が犯人であること","。"]},
    {"id":266,"level":"N2","grammar_display":"〜に決まっている","grammar_answer":"に決まっている","connection":"普通形（ナ形容詞・名詞） + に決まっている","sentence_parts":["あんなに努力したのだから、合格する","。"]},
    {"id":267,"level":"N2","grammar_display":"〜に違いない","grammar_answer":"に違いない","connection":"普通形（ナ形容詞・名詞） + に違いない","sentence_parts":["彼はきっと来る","。"]},
    {"id":268,"level":"N2","grammar_display":"〜のではないだろうか","grammar_answer":"ではないだろうか","connection":"普通形 + のではないだろうか","sentence_parts":["これは大きな問題になるの","。"]},
    // 10. 可能・不可能
    {"id":269,"level":"N1","grammar_display":"〜ないものか","grammar_answer":"ないものか","connection":"動詞ない形 + ものか","sentence_parts":["もう少し早く着け","。"]},
    {"id":270,"level":"N1","grammar_display":"〜ずに済む","grammar_answer":"ずに済んだ","connection":"動詞ない形（ない→ず） + に済む","sentence_parts":["バスがすぐ来たので、雨の中を待た","。"]},
    {"id":271,"level":"N1","grammar_display":"〜を禁じ得ない","grammar_answer":"を禁じ得なかった","connection":"名詞 + を禁じ得ない","sentence_parts":["彼の不幸な話に、涙","。"]},
    {"id":272,"level":"N1","grammar_display":"〜を余儀なくされる","grammar_answer":"を余儀なくされた","connection":"名詞 + を余儀なくされる","sentence_parts":["大雨で、試合は中止","。"]},
    {"id":273,"level":"N1","grammar_display":"〜にたえる","grammar_answer":"にたえる","connection":"動詞辞書形 / 名詞 + にたえる","sentence_parts":["この作品は鑑賞","ものだ。"]},
    {"id":274,"level":"N1","grammar_display":"〜べくもない","grammar_answer":"べくもない","connection":"動詞辞書形 + べくもない","sentence_parts":["優勝は望む","。"]},
    {"id":275,"level":"N2","grammar_display":"〜ざるを得ない","grammar_answer":"ざるを得ない","connection":"動詞ない形（ない→ざる） + を得ない","sentence_parts":["嫌な仕事でも、生活のためには続け","。"]},
    {"id":276,"level":"N2","grammar_display":"〜かねる","grammar_answer":"かねます","connection":"動詞ます形 + かねる","sentence_parts":["申し訳ありませんが、そのご要望にはお答えし","。"]},
    {"id":277,"level":"N2","grammar_display":"〜かねない","grammar_answer":"かねない","connection":"動詞ます形 + かねない","sentence_parts":["あんなにスピードを出したら、事故を起こし","。"]},
    {"id":278,"level":"N2","grammar_display":"〜恐れがある","grammar_answer":"恐れがある","connection":"動詞の辞書形 / 名詞の + 恐れがある","sentence_parts":["この地震で、津波が発生する","。"]},
    {"id":279,"level":"N2","grammar_display":"〜ようがない","grammar_answer":"ようがない","connection":"動詞ます形 + ようがない","sentence_parts":["ここまで壊れては、直し","。"]},
    {"id":280,"level":"N2","grammar_display":"〜にも〜ない","grammar_answer":"にも泣けない","connection":"動詞の辞書形 + に + 可能動詞の否定形","sentence_parts":["泣く","ほど、悲しかった。"]},
    {"id":281,"level":"N2","grammar_display":"〜（より）ほか（は）ない","grammar_answer":"ほかはない","connection":"動詞の辞書形 + ほか（は）ない","sentence_parts":["こうなったら、待つ","。"]},
    {"id":282,"level":"N2","grammar_display":"〜得る","grammar_answer":"得る","connection":"動詞ます形 + 得る","sentence_parts":["それはあり","話だ。"]},
    // 11. 状態・様子・意向
    {"id":283,"level":"N1","grammar_display":"〜ずにはおかない","grammar_answer":"ずにはおかない","connection":"動詞ない形（ない→ず） + にはおかない","sentence_parts":["彼のスピーチは聞く人を感動させ","。"]},
    {"id":284,"level":"N1","grammar_display":"〜てかなわない","grammar_answer":"てかなわない","connection":"動詞て形 / 形容詞て形 + かなわない","sentence_parts":["隣の工事がうるさく","。"]},
    {"id":285,"level":"N1","grammar_display":"〜ともなく","grammar_answer":"ともなく","connection":"動詞辞書形 + ともなく / ともなしに","sentence_parts":["テレビを見る","見ていたら、友達が出てきて驚いた。"]},
    {"id":286,"level":"N1","grammar_display":"〜ことなく","grammar_answer":"ことなく","connection":"動詞辞書形 + ことなく","sentence_parts":["彼は一度も休む","、研究を続けた。"]},
    {"id":287,"level":"N1","grammar_display":"〜ごとき","grammar_answer":"ごとき","connection":"名詞の / 動詞た形 + ごとき","sentence_parts":["彼","人物は、めったにいない。"]},
    {"id":288,"level":"N1","grammar_display":"〜ながらに","grammar_answer":"ながらに","connection":"動詞ます形 / 名詞 + ながらに","sentence_parts":["彼女は生まれ","優れた才能を持っている。"]},
    {"id":289,"level":"N1","grammar_display":"〜なりに","grammar_answer":"なりに","connection":"普通形（ナ形容詞・名詞 + なりに） + なりに","sentence_parts":["私","頑張ってみます。"]},
    {"id":290,"level":"N1","grammar_display":"〜ばかりになっている","grammar_answer":"ばかりになっている","connection":"動詞辞書形 + ばかりになっている","sentence_parts":["料理はできて、あとは食べる","。"]},
    {"id":291,"level":"N1","grammar_display":"〜とばかりに","grammar_answer":"とばかりに","connection":"命令形 / 意向形 + とばかりに","sentence_parts":["彼は「待ってました」","、話し始めた。"]},
    {"id":292,"level":"N1","grammar_display":"〜んばかりに","grammar_answer":"んばかりに","connection":"動詞ない形（ない→ん） + ばかりに","sentence_parts":["彼は「出ていけ」と言わ","、ドアを指さした。"]},
    {"id":293,"level":"N1","grammar_display":"〜んがために","grammar_answer":"んがために","connection":"動詞ない形（ない→ん） + がために","sentence_parts":["彼は夢を実現せ","、故郷を離れた。"]},
    {"id":294,"level":"N1","grammar_display":"〜んとする","grammar_answer":"んとする","connection":"動詞ない形（ない→ん） + とする","sentence_parts":["試合が終わら","瞬間に、逆転ゴールが決まった。"]},
    {"id":295,"level":"N1","grammar_display":"〜べく","grammar_answer":"べく","connection":"動詞辞書形 + べく","sentence_parts":["彼はプロの選手になる","、毎日厳しい練習をしている。"]},
    {"id":296,"level":"N1","grammar_display":"〜べくして","grammar_answer":"べくして","connection":"動詞辞書形 + べくして + 動詞た形","sentence_parts":["その事故は起こる","起こった。"]},
    {"id":297,"level":"N1","grammar_display":"〜をこめて","grammar_answer":"をこめて","connection":"名詞 + をこめて","sentence_parts":["感謝の気持ち","、プレゼントを贈ります。"]},
    {"id":298,"level":"N2","grammar_display":"〜てならない","grammar_answer":"てならない","connection":"動詞て形 / 形容詞て形 + ならない","sentence_parts":["試験の結果が気に（なって）","。"]},
    {"id":299,"level":"N2","grammar_display":"〜てたまらない","grammar_answer":"てたまらない","connection":"動詞て形 / 形容詞て形 + たまらない","sentence_parts":["彼に会いたく","。"]},
    {"id":300,"level":"N2","grammar_display":"〜てしかたがない","grammar_answer":"でしかたがない","connection":"動詞て形 / 形容詞て形 + しかたがない","sentence_parts":["暇","。"]},
    {"id":301,"level":"N2","grammar_display":"〜てはいられない","grammar_answer":"てはいられない","connection":"動詞て形 + は（も）いられない","sentence_parts":["もう時間がないから、のんびりし","。"]},
    {"id":302,"level":"N2","grammar_display":"〜てばかりいる","grammar_answer":"てばかりいる","connection":"動詞て形 + ばかりいる","sentence_parts":["彼は遊ん","。"]},
    {"id":303,"level":"N2","grammar_display":"〜ばかりだ","grammar_answer":"ばかりだ","connection":"動詞の辞書形 + ばかりだ","sentence_parts":["状況は悪くなる","。"]},
    {"id":304,"level":"N2","grammar_display":"〜ずにはいられない","grammar_answer":"ずにはいられない","connection":"動詞ない形（ない→ず） + にはいられない","sentence_parts":["彼の話を聞いて、笑わ","。"]},
    {"id":305,"level":"N2","grammar_display":"〜一方だ","grammar_answer":"一方だ","connection":"動詞の辞書形 + 一方だ","sentence_parts":["物価は上がる","。"]},
    {"id":306,"level":"N2","grammar_display":"〜つもりだ","grammar_answer":"つもりだ","connection":"動詞の辞書形/ている形/た形 / 名詞の + つもりだ","sentence_parts":["まだ若い","が、もう年だ。"]},
    {"id":307,"level":"N2","grammar_display":"〜（よ）うとする","grammar_answer":"うとした","connection":"動詞の意向形 + とする","sentence_parts":["出かけよ","とき、電話が鳴った。"]},
    {"id":308,"level":"N2","grammar_display":"〜ながら","grammar_answer":"ながら","connection":"動詞ます形 + ながら","sentence_parts":["音楽を聞き","、勉強する。"]},
    {"id":309,"level":"N2","grammar_display":"〜つつ","grammar_answer":"つつ","connection":"動詞ます形 + つつ","sentence_parts":["テレビを見","、食事をする。"]},
    {"id":310,"level":"N2","grammar_display":"〜つつある","grammar_answer":"つつある","connection":"動詞ます形 + つつある","sentence_parts":["景気は回復し","。"]},
    {"id":311,"level":"N2","grammar_display":"〜ば〜ほど","grammar_answer":"ば","connection":"動詞ば形 / 形容詞ければ + 同じ動詞/形容詞 + ほど","sentence_parts":["日本語は勉強すれ","、面白くなる。"]},
    {"id":312,"level":"N2","grammar_display":"〜中を","grammar_answer":"中を","connection":"名詞 / 形容詞 + 中を","sentence_parts":["お忙しい","、お越しいただきありがとうございます。"]},
    {"id":313,"level":"N2","grammar_display":"〜きり","grammar_answer":"きり","connection":"動詞た形 + きり","sentence_parts":["彼は部屋に入った","、出てこない。"]},
    {"id":314,"level":"N2","grammar_display":"〜かのようだ","grammar_answer":"かのように","connection":"普通形 + かのようだ","sentence_parts":["彼はまるで全てを知っている","話す。"]},
    {"id":315,"level":"N2","grammar_display":"〜ふりをする","grammar_answer":"ふりをした","connection":"普通形（ナ形容詞な / 名詞の） + ふりをする","sentence_parts":["彼は聞こえない","。"]},
    {"id":316,"level":"N2","grammar_display":"〜ところだった","grammar_answer":"ところだった","connection":"動詞の辞書形/ない形 + ところだった","sentence_parts":["もう少しで、事故を起こす","。"]},
    {"id":317,"level":"N2","grammar_display":"〜ことになっている","grammar_answer":"ことになっている","connection":"動詞の辞書形/ない形 / 名詞という + ことになっている","sentence_parts":["明日、会議が開かれる","。"]},
    {"id":318,"level":"N2","grammar_display":"〜ようになっている","grammar_answer":"ようになっている","connection":"動詞の辞書形/ない形 + ようになっている","sentence_parts":["このドアは自動で開く","。"]},
    // 12. 接尾辞・複合動詞
    {"id":319,"level":"N1","grammar_display":"〜そこなう","grammar_answer":"そこなった","connection":"動詞ます形 + そこなう","sentence_parts":["バスに乗り","、会社に遅刻してしまった。"]},
    {"id":320,"level":"N1","grammar_display":"〜こなす","grammar_answer":"こなした","connection":"動詞ます形 + こなす","sentence_parts":["彼は難しい役を完璧に演じ","。"]},
    {"id":321,"level":"N1","grammar_display":"〜あげる","grammar_answer":"あげた","connection":"動詞ます形 + あげる","sentence_parts":["一晩でこの本を読み","。"]},
    {"id":322,"level":"N2","grammar_display":"〜抜く","grammar_answer":"抜いた","connection":"動詞ます形 + 抜く","sentence_parts":["彼はマラソンを最後まで走り","。"]},
    {"id":323,"level":"N2","grammar_display":"〜かける","grammar_answer":"かけの","connection":"動詞ます形 + かけ","sentence_parts":["読み","本が机の上に置いてある。"]},
    {"id":324,"level":"N2","grammar_display":"〜がち","grammar_answer":"がちだ","connection":"動詞ます形 / 名詞 + がち","sentence_parts":["私は子供のころ、病気をし","。"]},
    {"id":325,"level":"N2","grammar_display":"〜がる","grammar_answer":"がっている","connection":"形容詞語幹 + がる","sentence_parts":["妹は犬を怖","。"]},
    {"id":326,"level":"N2","grammar_display":"〜気味","grammar_answer":"気味で","connection":"動詞ます形 / 名詞 + 気味","sentence_parts":["最近、少し疲れ","、仕事がなかなか進まない。"]},
    {"id":327,"level":"N2","grammar_display":"〜きる","grammar_answer":"きれない","connection":"動詞ます形 + きる / きれる / きれない","sentence_parts":["料理がたくさんありすぎて、食べ","。"]},
    {"id":328,"level":"N2","grammar_display":"〜げ","grammar_answer":"げな","connection":"イ形容詞語幹 / ナ形容詞語幹 + げ","sentence_parts":["彼は何か言いたそうに、寂し","表情をしていた。"]},
    {"id":329,"level":"N2","grammar_display":"〜だらけ","grammar_answer":"だらけだ","connection":"名詞 + だらけ","sentence_parts":["このレポートは間違い","。"]},
    {"id":330,"level":"N2","grammar_display":"〜っぽい","grammar_answer":"っぽくて","connection":"動詞ます形 / 名詞 / イ形容詞語幹 + っぽい","sentence_parts":["このコート、デザインはいいんだけど、生地が安","いやだ。"]},
    // 13. その他
    {"id":331,"level":"N2","grammar_display":"〜向き","grammar_answer":"向きだ","connection":"名詞 + 向き","sentence_parts":["この本は子供","。"]},
    {"id":332,"level":"N2","grammar_display":"〜向け","grammar_answer":"向けに","connection":"名詞 + 向け","sentence_parts":["この製品は海外","作られている。"]},
    {"id":333,"level":"N2","grammar_display":"〜ずつ","grammar_answer":"ずつ","connection":"数量詞 + ずつ","sentence_parts":["一人に三つ","配ってください。"]},
    {"id":334,"level":"N2","grammar_display":"〜おきに","grammar_answer":"おきに","connection":"数量詞 + おきに","sentence_parts":["このバスは10分","来る。"]},
    {"id":335,"level":"N2","grammar_display":"〜ごとに","grammar_answer":"ごとに","connection":"名詞 / 動詞の辞書形 + ごとに","sentence_parts":["一年","、日本語が上手になる。"]},
    {"id":336,"level":"N2","grammar_display":"〜なんて","grammar_answer":"なんて","connection":"普通形 + なんて / なんか","sentence_parts":["彼が犯人だ","、信じられない。"]},
    {"id":337,"level":"N2","grammar_display":"〜なんか","grammar_answer":"なんか","connection":"名詞 + なんか","sentence_parts":["私","、まだまだです。"]},
    {"id":338,"level":"N2","grammar_display":"〜っけ","grammar_answer":"っけ","connection":"普通形（た形） + っけ","sentence_parts":["明日の会議、何時からだ","。"]},
    {"id":339,"level":"N2","grammar_display":"〜（よ）うではないか","grammar_answer":"うではないか","connection":"動詞の意向形 + ではないか","sentence_parts":["目標達成のために、みんなで頑張ろ","。"]},
    {"id":340,"level":"N1","grammar_display":"〜まみれ","grammar_answer":"まみれに","connection":"名詞 + まみれ","sentence_parts":["子供たちは、公園で泥","なって遊んでいた。"]},
    {"id":341,"level":"N1","grammar_display":"〜ずくめ","grammar_answer":"ずくめ","connection":"名詞 + ずくめ","sentence_parts":["今日の彼女は、指輪もネックレスもダイヤ","だ。"]}
];
